### PR TITLE
dreport: Added support to collect LDAP config data

### PR DESCRIPTION
**Pull request by nkotania**
LDAP related detailed data will be collected as part of BMC user initiated Dump.
This commit will add 2 new file:
1. usrmgrldap.log (size: 3.1K)
2. nslcd.log (size: 526B)

Tested By:
      Tested by collecting BMC dump.

Change-Id: I09e35379935838c6f06d8604303f16a1febc8d3a

Upstream Commit: https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/68090

### CODE REVIEW

**Comment by geissonator** [comment]
add to approvelist

**Comment by geissonator** [comment]
Please point to upstream commit for this.

**Comment by nkotania** [comment]
> Please point to upstream commit for this.

Added.

**Comment by devenrao** [comment]
why there are 3 commits for 1 change last 2 commits are dummy or not needed

**Comment by nkotania** [comment]
Closing this PR, created another PR for the same.
New PR: https://github.com/ibm-openbmc/phosphor-debug-collector/pull/133

**Pull request closed without merging**
